import 'package:flutter/material.dart';

import '../../models/remote_models.dart';
import '../../widgets/pad_workspace_view.dart';
import '../../widgets/remote_workspace_view.dart';
import '../../widgets/workspace/workspace_controller.dart';
import 'home_workspace_shell_data.dart';

typedef ProjectOpenCallback = void Function(ProjectInfo project);
typedef TerminalOpenCallback = void Function(TerminalInfo terminal);
typedef WorktreeOpenCallback = void Function(RemoteWorktreeInfo worktree);

class HomeWorkspaceBuilder {
  const HomeWorkspaceBuilder({required this.padLayoutMinWidth});

  final double padLayoutMinWidth;

  Widget build({
    required BuildContext context,
    required double topInset,
    required String workspaceMode,
    required bool connected,
    required int? latencyMs,
    required String deviceName,
    required List<ProjectInfo> projects,
    required String? selectedProjectId,
    required bool projectListLoaded,
    required String? selectedWorktreeId,
    required String? activeTerminalId,
    required bool hasCurrentTerminal,
    required WorkspaceShellData shellData,
    required Widget terminalBody,
    required VoidCallback onShowTerminal,
    required VoidCallback onShowStats,
    required VoidCallback onShowFiles,
    required VoidCallback onShowReview,
    required VoidCallback onShowSsh,
    required VoidCallback onShowGit,
    required void Function(String op, Map<String, dynamic> args) onGitAction,
    required VoidCallback onRefreshGit,
    required RemoteGitDiff? gitDiff,
    required String? reviewSelectedPath,
    required ValueChanged<String> onSelectReviewFile,
    required String? editingFilePath,
    required TextEditingController fileEditorController,
    required bool fileEditorLoading,
    required bool fileEditorSaving,
    required bool fileEditorEditing,
    required bool fileEditorEditable,
    required VoidCallback onEditFile,
    required VoidCallback onSaveFile,
    required VoidCallback onCancelFileEdit,
    required VoidCallback onCloseFileEditor,
    required VoidCallback onBack,
    required VoidCallback onEditProject,
    required VoidCallback onAddProject,
    required VoidCallback onRemoveProject,
    required ProjectOpenCallback onSelectProject,
    required WorktreeOpenCallback onSelectWorktree,
    required VoidCallback onCreateWorktree,
    required TerminalOpenCallback onSelectTerminal,
    required VoidCallback onRefreshLists,
    required VoidCallback onCreateTerminal,
    required VoidCallback onCloseCurrentTerminal,
    required TerminalOpenCallback onCloseTerminal,
    required Future<void> Function(TerminalInfo terminal) onRenameSession,
    required VoidCallback onRebuildTerminal,
    required VoidCallback onOpenTerminalSwitcher,
    required ValueChanged<String> onRequestProjectFiles,
    required ValueChanged<RemoteFileEntry> onOpenProjectFile,
    required VoidCallback onOpenProjectHome,
    required VoidCallback onOpenProjectRoot,
    required VoidCallback onOpenProjectVolumes,
    required ValueChanged<RemoteFileEntry> onRenameProjectFile,
    required ValueChanged<RemoteFileEntry> onCopyProjectFilePath,
    required ValueChanged<RemoteFileEntry> onDeleteProjectFile,
  }) {
    if (MediaQuery.of(context).size.width >= padLayoutMinWidth) {
      return PadWorkspaceView(
        controller: WorkspaceController(
          topInset: topInset,
          workspaceMode: workspaceMode,
          connected: connected,
          latencyMs: latencyMs,
          deviceName: deviceName,
          projects: projects,
          selectedProjectId: selectedProjectId,
          worktrees: shellData.worktrees,
          selectedWorktreeId: selectedWorktreeId,
          terminals: shellData.terminals,
          activeTerminalId: activeTerminalId,
          aiStats: shellData.aiStats,
          aiStatsLoading: shellData.aiStatsLoading,
          gitStatus: shellData.gitStatus,
          onGitAction: onGitAction,
          onRefreshGit: onRefreshGit,
          aiSessions: shellData.aiSessions,
          sshProfiles: shellData.sshProfiles,
          gitDiff: gitDiff,
          reviewSelectedPath: reviewSelectedPath,
          onSelectReviewFile: onSelectReviewFile,
          editingFilePath: editingFilePath,
          fileEditorController: fileEditorController,
          fileEditorLoading: fileEditorLoading,
          fileEditorSaving: fileEditorSaving,
          fileEditorEditing: fileEditorEditing,
          fileEditorEditable: fileEditorEditable,
          onEditFile: onEditFile,
          onSaveFile: onSaveFile,
          onCancelFileEdit: onCancelFileEdit,
          onCloseFileEditor: onCloseFileEditor,
          projectFilesPath: shellData.projectFilesPath,
          projectFilesParent: shellData.projectFilesParent,
          projectFileEntries: shellData.projectFileEntries,
          projectFilesLoading: shellData.projectFilesLoading,
          terminalBody: terminalBody,
          onShowTerminal: onShowTerminal,
          onShowStats: onShowStats,
          onShowFiles: onShowFiles,
          onShowReview: onShowReview,
          onShowSsh: onShowSsh,
          onShowGit: onShowGit,
          onEditProject: onEditProject,
          onAddProject: onAddProject,
          onRemoveProject: onRemoveProject,
          onSelectProject: onSelectProject,
          onSelectWorktree: onSelectWorktree,
          onCreateWorktree: onCreateWorktree,
          onSelectTerminal: onSelectTerminal,
          onCreateTerminal: onCreateTerminal,
          onCloseTerminal: onCloseTerminal,
          onRenameSession: (terminal) {
            onRenameSession(terminal);
          },
          onRequestProjectFiles: onRequestProjectFiles,
          onOpenProjectFile: onOpenProjectFile,
          onOpenProjectHome: onOpenProjectHome,
          onOpenProjectRoot: onOpenProjectRoot,
          onOpenProjectVolumes: onOpenProjectVolumes,
          onRenameProjectFile: onRenameProjectFile,
          onCopyProjectFilePath: onCopyProjectFilePath,
          onDeleteProjectFile: onDeleteProjectFile,
        ),
      );
    }

    return RemoteWorkspaceView(
      topInset: topInset,
      workspaceMode: workspaceMode,
      connected: connected,
      latencyMs: latencyMs,
      projects: projects,
      selectedProjectId: selectedProjectId,
      projectListLoaded: projectListLoaded,
      terminals: shellData.terminals,
      activeTerminalId: activeTerminalId,
      hasCurrentTerminal: hasCurrentTerminal,
      aiStats: shellData.aiStats,
      aiStatsLoading: shellData.aiStatsLoading,
      projectFilesPath: shellData.projectFilesPath,
      projectFilesParent: shellData.projectFilesParent,
      projectFileEntries: shellData.projectFileEntries,
      projectFilesLoading: shellData.projectFilesLoading,
      terminalBody: terminalBody,
      onShowTerminal: onShowTerminal,
      onShowStats: onShowStats,
      onShowFiles: onShowFiles,
      onBack: onBack,
      onEditProject: onEditProject,
      onAddProject: onAddProject,
      onRemoveProject: onRemoveProject,
      onSelectProject: onSelectProject,
      onSelectTerminal: onSelectTerminal,
      onRefreshLists: onRefreshLists,
      onCreateTerminal: onCreateTerminal,
      onCloseCurrentTerminal: onCloseCurrentTerminal,
      onRebuildTerminal: onRebuildTerminal,
      onOpenTerminalSwitcher: onOpenTerminalSwitcher,
      onRequestProjectFiles: onRequestProjectFiles,
      onOpenProjectFile: onOpenProjectFile,
      onOpenProjectHome: onOpenProjectHome,
      onOpenProjectRoot: onOpenProjectRoot,
      onOpenProjectVolumes: onOpenProjectVolumes,
      onRenameProjectFile: onRenameProjectFile,
      onCopyProjectFilePath: onCopyProjectFilePath,
      onDeleteProjectFile: onDeleteProjectFile,
    );
  }
}
