use gpui::SharedString;
use gpui_component::{Icon, IconNamed};

#[allow(dead_code)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum HeroIconName {
    AcademicCap,
    AdjustmentsHorizontal,
    AdjustmentsVertical,
    ArchiveBoxArrowDown,
    ArchiveBoxXMark,
    ArchiveBox,
    ArrowDownCircle,
    ArrowDownLeft,
    ArrowDownOnSquareStack,
    ArrowDownOnSquare,
    ArrowDownRight,
    ArrowDownTray,
    ArrowDown,
    ArrowLeftCircle,
    ArrowLeftEndOnRectangle,
    ArrowLeftOnRectangle,
    ArrowLeftStartOnRectangle,
    ArrowLeft,
    ArrowLongDown,
    ArrowLongLeft,
    ArrowLongRight,
    ArrowLongUp,
    ArrowPathRoundedSquare,
    ArrowPath,
    ArrowRightCircle,
    ArrowRightEndOnRectangle,
    ArrowRightOnRectangle,
    ArrowRightStartOnRectangle,
    ArrowRight,
    ArrowSmallDown,
    ArrowSmallLeft,
    ArrowSmallRight,
    ArrowSmallUp,
    ArrowTopRightOnSquare,
    ArrowTrendingDown,
    ArrowTrendingUp,
    ArrowTurnDownLeft,
    ArrowTurnDownRight,
    ArrowTurnLeftDown,
    ArrowTurnLeftUp,
    ArrowTurnRightDown,
    ArrowTurnRightUp,
    ArrowTurnUpLeft,
    ArrowTurnUpRight,
    ArrowUpCircle,
    ArrowUpLeft,
    ArrowUpOnSquareStack,
    ArrowUpOnSquare,
    ArrowUpRight,
    ArrowUpTray,
    ArrowUp,
    ArrowUturnDown,
    ArrowUturnLeft,
    ArrowUturnRight,
    ArrowUturnUp,
    ArrowsPointingIn,
    ArrowsPointingOut,
    ArrowsRightLeft,
    ArrowsUpDown,
    AtSymbol,
    Backspace,
    Backward,
    Banknotes,
    Bars2,
    Bars3BottomLeft,
    Bars3BottomRight,
    Bars3CenterLeft,
    Bars3,
    Bars4,
    BarsArrowDown,
    BarsArrowUp,
    Battery0,
    Battery100,
    Battery50,
    Beaker,
    BellAlert,
    BellSlash,
    BellSnooze,
    Bell,
    Bold,
    BoltSlash,
    Bolt,
    BookOpen,
    BookmarkSlash,
    BookmarkSquare,
    Bookmark,
    Briefcase,
    BugAnt,
    BuildingLibrary,
    BuildingOffice2,
    BuildingOffice,
    BuildingStorefront,
    Cake,
    Calculator,
    CalendarDateRange,
    CalendarDays,
    Calendar,
    Camera,
    ChartBarSquare,
    ChartBar,
    ChartPie,
    ChatBubbleBottomCenterText,
    ChatBubbleBottomCenter,
    ChatBubbleLeftEllipsis,
    ChatBubbleLeftRight,
    ChatBubbleLeft,
    ChatBubbleOvalLeftEllipsis,
    ChatBubbleOvalLeft,
    CheckBadge,
    CheckCircle,
    Check,
    ChevronDoubleDown,
    ChevronDoubleLeft,
    ChevronDoubleRight,
    ChevronDoubleUp,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUpDown,
    ChevronUp,
    CircleStack,
    ClipboardDocumentCheck,
    ClipboardDocumentList,
    ClipboardDocument,
    Clipboard,
    Clock,
    CloudArrowDown,
    CloudArrowUp,
    Cloud,
    CodeBracketSquare,
    CodeBracket,
    Cog6Tooth,
    Cog8Tooth,
    Cog,
    CommandLine,
    ComputerDesktop,
    CpuChip,
    CreditCard,
    CubeTransparent,
    Cube,
    CurrencyBangladeshi,
    CurrencyDollar,
    CurrencyEuro,
    CurrencyPound,
    CurrencyRupee,
    CurrencyYen,
    CursorArrowRays,
    CursorArrowRipple,
    DevicePhoneMobile,
    DeviceTablet,
    Divide,
    DocumentArrowDown,
    DocumentArrowUp,
    DocumentChartBar,
    DocumentCheck,
    DocumentCurrencyBangladeshi,
    DocumentCurrencyDollar,
    DocumentCurrencyEuro,
    DocumentCurrencyPound,
    DocumentCurrencyRupee,
    DocumentCurrencyYen,
    DocumentDuplicate,
    DocumentMagnifyingGlass,
    DocumentMinus,
    DocumentPlus,
    DocumentText,
    Document,
    EllipsisHorizontalCircle,
    EllipsisHorizontal,
    EllipsisVertical,
    EnvelopeOpen,
    Envelope,
    Equals,
    ExclamationCircle,
    ExclamationTriangle,
    EyeDropper,
    EyeSlash,
    Eye,
    FaceFrown,
    FaceSmile,
    Film,
    FingerPrint,
    Fire,
    Flag,
    FolderArrowDown,
    FolderMinus,
    FolderOpen,
    FolderPlus,
    Folder,
    Forward,
    Funnel,
    Gif,
    GiftTop,
    Gift,
    GlobeAlt,
    GlobeAmericas,
    GlobeAsiaAustralia,
    GlobeEuropeAfrica,
    H1,
    H2,
    H3,
    HandRaised,
    HandThumbDown,
    HandThumbUp,
    Hashtag,
    Heart,
    HomeModern,
    Home,
    Identification,
    InboxArrowDown,
    InboxStack,
    Inbox,
    InformationCircle,
    Italic,
    Key,
    Language,
    Lifebuoy,
    LightBulb,
    LinkSlash,
    Link,
    ListBullet,
    LockClosed,
    LockOpen,
    MagnifyingGlassCircle,
    MagnifyingGlassMinus,
    MagnifyingGlassPlus,
    MagnifyingGlass,
    MapPin,
    Map,
    Megaphone,
    Microphone,
    MinusCircle,
    MinusSmall,
    Minus,
    Moon,
    MusicalNote,
    Newspaper,
    NoSymbol,
    NumberedList,
    PaintBrush,
    PaperAirplane,
    PaperClip,
    PauseCircle,
    Pause,
    PencilSquare,
    Pencil,
    PercentBadge,
    PhoneArrowDownLeft,
    PhoneArrowUpRight,
    PhoneXMark,
    Phone,
    Photo,
    PlayCircle,
    PlayPause,
    Play,
    PlusCircle,
    PlusSmall,
    Plus,
    Power,
    PresentationChartBar,
    PresentationChartLine,
    Printer,
    PuzzlePiece,
    QrCode,
    QuestionMarkCircle,
    QueueList,
    Radio,
    ReceiptPercent,
    ReceiptRefund,
    RectangleGroup,
    RectangleStack,
    RocketLaunch,
    Rss,
    Scale,
    Scissors,
    ServerStack,
    Server,
    Share,
    ShieldCheck,
    ShieldExclamation,
    ShoppingBag,
    ShoppingCart,
    SignalSlash,
    Signal,
    Slash,
    Sparkles,
    SpeakerWave,
    SpeakerXMark,
    Square2Stack,
    Square3Stack3d,
    Squares2x2,
    SquaresPlus,
    Star,
    StopCircle,
    Stop,
    Strikethrough,
    Sun,
    Swatch,
    TableCells,
    Tag,
    Ticket,
    Trash,
    Trophy,
    Truck,
    Tv,
    Underline,
    UserCircle,
    UserGroup,
    UserMinus,
    UserPlus,
    User,
    Users,
    Variable,
    VideoCameraSlash,
    VideoCamera,
    ViewColumns,
    ViewfinderCircle,
    Wallet,
    Wifi,
    Window,
    WrenchScrewdriver,
    Wrench,
    XCircle,
    XMark,
}

impl HeroIconName {
    #[allow(dead_code)]
    pub const ALL: &'static [Self] = &[
        Self::AcademicCap,
        Self::AdjustmentsHorizontal,
        Self::AdjustmentsVertical,
        Self::ArchiveBoxArrowDown,
        Self::ArchiveBoxXMark,
        Self::ArchiveBox,
        Self::ArrowDownCircle,
        Self::ArrowDownLeft,
        Self::ArrowDownOnSquareStack,
        Self::ArrowDownOnSquare,
        Self::ArrowDownRight,
        Self::ArrowDownTray,
        Self::ArrowDown,
        Self::ArrowLeftCircle,
        Self::ArrowLeftEndOnRectangle,
        Self::ArrowLeftOnRectangle,
        Self::ArrowLeftStartOnRectangle,
        Self::ArrowLeft,
        Self::ArrowLongDown,
        Self::ArrowLongLeft,
        Self::ArrowLongRight,
        Self::ArrowLongUp,
        Self::ArrowPathRoundedSquare,
        Self::ArrowPath,
        Self::ArrowRightCircle,
        Self::ArrowRightEndOnRectangle,
        Self::ArrowRightOnRectangle,
        Self::ArrowRightStartOnRectangle,
        Self::ArrowRight,
        Self::ArrowSmallDown,
        Self::ArrowSmallLeft,
        Self::ArrowSmallRight,
        Self::ArrowSmallUp,
        Self::ArrowTopRightOnSquare,
        Self::ArrowTrendingDown,
        Self::ArrowTrendingUp,
        Self::ArrowTurnDownLeft,
        Self::ArrowTurnDownRight,
        Self::ArrowTurnLeftDown,
        Self::ArrowTurnLeftUp,
        Self::ArrowTurnRightDown,
        Self::ArrowTurnRightUp,
        Self::ArrowTurnUpLeft,
        Self::ArrowTurnUpRight,
        Self::ArrowUpCircle,
        Self::ArrowUpLeft,
        Self::ArrowUpOnSquareStack,
        Self::ArrowUpOnSquare,
        Self::ArrowUpRight,
        Self::ArrowUpTray,
        Self::ArrowUp,
        Self::ArrowUturnDown,
        Self::ArrowUturnLeft,
        Self::ArrowUturnRight,
        Self::ArrowUturnUp,
        Self::ArrowsPointingIn,
        Self::ArrowsPointingOut,
        Self::ArrowsRightLeft,
        Self::ArrowsUpDown,
        Self::AtSymbol,
        Self::Backspace,
        Self::Backward,
        Self::Banknotes,
        Self::Bars2,
        Self::Bars3BottomLeft,
        Self::Bars3BottomRight,
        Self::Bars3CenterLeft,
        Self::Bars3,
        Self::Bars4,
        Self::BarsArrowDown,
        Self::BarsArrowUp,
        Self::Battery0,
        Self::Battery100,
        Self::Battery50,
        Self::Beaker,
        Self::BellAlert,
        Self::BellSlash,
        Self::BellSnooze,
        Self::Bell,
        Self::Bold,
        Self::BoltSlash,
        Self::Bolt,
        Self::BookOpen,
        Self::BookmarkSlash,
        Self::BookmarkSquare,
        Self::Bookmark,
        Self::Briefcase,
        Self::BugAnt,
        Self::BuildingLibrary,
        Self::BuildingOffice2,
        Self::BuildingOffice,
        Self::BuildingStorefront,
        Self::Cake,
        Self::Calculator,
        Self::CalendarDateRange,
        Self::CalendarDays,
        Self::Calendar,
        Self::Camera,
        Self::ChartBarSquare,
        Self::ChartBar,
        Self::ChartPie,
        Self::ChatBubbleBottomCenterText,
        Self::ChatBubbleBottomCenter,
        Self::ChatBubbleLeftEllipsis,
        Self::ChatBubbleLeftRight,
        Self::ChatBubbleLeft,
        Self::ChatBubbleOvalLeftEllipsis,
        Self::ChatBubbleOvalLeft,
        Self::CheckBadge,
        Self::CheckCircle,
        Self::Check,
        Self::ChevronDoubleDown,
        Self::ChevronDoubleLeft,
        Self::ChevronDoubleRight,
        Self::ChevronDoubleUp,
        Self::ChevronDown,
        Self::ChevronLeft,
        Self::ChevronRight,
        Self::ChevronUpDown,
        Self::ChevronUp,
        Self::CircleStack,
        Self::ClipboardDocumentCheck,
        Self::ClipboardDocumentList,
        Self::ClipboardDocument,
        Self::Clipboard,
        Self::Clock,
        Self::CloudArrowDown,
        Self::CloudArrowUp,
        Self::Cloud,
        Self::CodeBracketSquare,
        Self::CodeBracket,
        Self::Cog6Tooth,
        Self::Cog8Tooth,
        Self::Cog,
        Self::CommandLine,
        Self::ComputerDesktop,
        Self::CpuChip,
        Self::CreditCard,
        Self::CubeTransparent,
        Self::Cube,
        Self::CurrencyBangladeshi,
        Self::CurrencyDollar,
        Self::CurrencyEuro,
        Self::CurrencyPound,
        Self::CurrencyRupee,
        Self::CurrencyYen,
        Self::CursorArrowRays,
        Self::CursorArrowRipple,
        Self::DevicePhoneMobile,
        Self::DeviceTablet,
        Self::Divide,
        Self::DocumentArrowDown,
        Self::DocumentArrowUp,
        Self::DocumentChartBar,
        Self::DocumentCheck,
        Self::DocumentCurrencyBangladeshi,
        Self::DocumentCurrencyDollar,
        Self::DocumentCurrencyEuro,
        Self::DocumentCurrencyPound,
        Self::DocumentCurrencyRupee,
        Self::DocumentCurrencyYen,
        Self::DocumentDuplicate,
        Self::DocumentMagnifyingGlass,
        Self::DocumentMinus,
        Self::DocumentPlus,
        Self::DocumentText,
        Self::Document,
        Self::EllipsisHorizontalCircle,
        Self::EllipsisHorizontal,
        Self::EllipsisVertical,
        Self::EnvelopeOpen,
        Self::Envelope,
        Self::Equals,
        Self::ExclamationCircle,
        Self::ExclamationTriangle,
        Self::EyeDropper,
        Self::EyeSlash,
        Self::Eye,
        Self::FaceFrown,
        Self::FaceSmile,
        Self::Film,
        Self::FingerPrint,
        Self::Fire,
        Self::Flag,
        Self::FolderArrowDown,
        Self::FolderMinus,
        Self::FolderOpen,
        Self::FolderPlus,
        Self::Folder,
        Self::Forward,
        Self::Funnel,
        Self::Gif,
        Self::GiftTop,
        Self::Gift,
        Self::GlobeAlt,
        Self::GlobeAmericas,
        Self::GlobeAsiaAustralia,
        Self::GlobeEuropeAfrica,
        Self::H1,
        Self::H2,
        Self::H3,
        Self::HandRaised,
        Self::HandThumbDown,
        Self::HandThumbUp,
        Self::Hashtag,
        Self::Heart,
        Self::HomeModern,
        Self::Home,
        Self::Identification,
        Self::InboxArrowDown,
        Self::InboxStack,
        Self::Inbox,
        Self::InformationCircle,
        Self::Italic,
        Self::Key,
        Self::Language,
        Self::Lifebuoy,
        Self::LightBulb,
        Self::LinkSlash,
        Self::Link,
        Self::ListBullet,
        Self::LockClosed,
        Self::LockOpen,
        Self::MagnifyingGlassCircle,
        Self::MagnifyingGlassMinus,
        Self::MagnifyingGlassPlus,
        Self::MagnifyingGlass,
        Self::MapPin,
        Self::Map,
        Self::Megaphone,
        Self::Microphone,
        Self::MinusCircle,
        Self::MinusSmall,
        Self::Minus,
        Self::Moon,
        Self::MusicalNote,
        Self::Newspaper,
        Self::NoSymbol,
        Self::NumberedList,
        Self::PaintBrush,
        Self::PaperAirplane,
        Self::PaperClip,
        Self::PauseCircle,
        Self::Pause,
        Self::PencilSquare,
        Self::Pencil,
        Self::PercentBadge,
        Self::PhoneArrowDownLeft,
        Self::PhoneArrowUpRight,
        Self::PhoneXMark,
        Self::Phone,
        Self::Photo,
        Self::PlayCircle,
        Self::PlayPause,
        Self::Play,
        Self::PlusCircle,
        Self::PlusSmall,
        Self::Plus,
        Self::Power,
        Self::PresentationChartBar,
        Self::PresentationChartLine,
        Self::Printer,
        Self::PuzzlePiece,
        Self::QrCode,
        Self::QuestionMarkCircle,
        Self::QueueList,
        Self::Radio,
        Self::ReceiptPercent,
        Self::ReceiptRefund,
        Self::RectangleGroup,
        Self::RectangleStack,
        Self::RocketLaunch,
        Self::Rss,
        Self::Scale,
        Self::Scissors,
        Self::ServerStack,
        Self::Server,
        Self::Share,
        Self::ShieldCheck,
        Self::ShieldExclamation,
        Self::ShoppingBag,
        Self::ShoppingCart,
        Self::SignalSlash,
        Self::Signal,
        Self::Slash,
        Self::Sparkles,
        Self::SpeakerWave,
        Self::SpeakerXMark,
        Self::Square2Stack,
        Self::Square3Stack3d,
        Self::Squares2x2,
        Self::SquaresPlus,
        Self::Star,
        Self::StopCircle,
        Self::Stop,
        Self::Strikethrough,
        Self::Sun,
        Self::Swatch,
        Self::TableCells,
        Self::Tag,
        Self::Ticket,
        Self::Trash,
        Self::Trophy,
        Self::Truck,
        Self::Tv,
        Self::Underline,
        Self::UserCircle,
        Self::UserGroup,
        Self::UserMinus,
        Self::UserPlus,
        Self::User,
        Self::Users,
        Self::Variable,
        Self::VideoCameraSlash,
        Self::VideoCamera,
        Self::ViewColumns,
        Self::ViewfinderCircle,
        Self::Wallet,
        Self::Wifi,
        Self::Window,
        Self::WrenchScrewdriver,
        Self::Wrench,
        Self::XCircle,
        Self::XMark,
    ];

    pub fn file_name(self) -> &'static str {
        match self {
            Self::AcademicCap => "academic-cap.svg",
            Self::AdjustmentsHorizontal => "adjustments-horizontal.svg",
            Self::AdjustmentsVertical => "adjustments-vertical.svg",
            Self::ArchiveBoxArrowDown => "archive-box-arrow-down.svg",
            Self::ArchiveBoxXMark => "archive-box-x-mark.svg",
            Self::ArchiveBox => "archive-box.svg",
            Self::ArrowDownCircle => "arrow-down-circle.svg",
            Self::ArrowDownLeft => "arrow-down-left.svg",
            Self::ArrowDownOnSquareStack => "arrow-down-on-square-stack.svg",
            Self::ArrowDownOnSquare => "arrow-down-on-square.svg",
            Self::ArrowDownRight => "arrow-down-right.svg",
            Self::ArrowDownTray => "arrow-down-tray.svg",
            Self::ArrowDown => "arrow-down.svg",
            Self::ArrowLeftCircle => "arrow-left-circle.svg",
            Self::ArrowLeftEndOnRectangle => "arrow-left-end-on-rectangle.svg",
            Self::ArrowLeftOnRectangle => "arrow-left-on-rectangle.svg",
            Self::ArrowLeftStartOnRectangle => "arrow-left-start-on-rectangle.svg",
            Self::ArrowLeft => "arrow-left.svg",
            Self::ArrowLongDown => "arrow-long-down.svg",
            Self::ArrowLongLeft => "arrow-long-left.svg",
            Self::ArrowLongRight => "arrow-long-right.svg",
            Self::ArrowLongUp => "arrow-long-up.svg",
            Self::ArrowPathRoundedSquare => "arrow-path-rounded-square.svg",
            Self::ArrowPath => "arrow-path.svg",
            Self::ArrowRightCircle => "arrow-right-circle.svg",
            Self::ArrowRightEndOnRectangle => "arrow-right-end-on-rectangle.svg",
            Self::ArrowRightOnRectangle => "arrow-right-on-rectangle.svg",
            Self::ArrowRightStartOnRectangle => "arrow-right-start-on-rectangle.svg",
            Self::ArrowRight => "arrow-right.svg",
            Self::ArrowSmallDown => "arrow-small-down.svg",
            Self::ArrowSmallLeft => "arrow-small-left.svg",
            Self::ArrowSmallRight => "arrow-small-right.svg",
            Self::ArrowSmallUp => "arrow-small-up.svg",
            Self::ArrowTopRightOnSquare => "arrow-top-right-on-square.svg",
            Self::ArrowTrendingDown => "arrow-trending-down.svg",
            Self::ArrowTrendingUp => "arrow-trending-up.svg",
            Self::ArrowTurnDownLeft => "arrow-turn-down-left.svg",
            Self::ArrowTurnDownRight => "arrow-turn-down-right.svg",
            Self::ArrowTurnLeftDown => "arrow-turn-left-down.svg",
            Self::ArrowTurnLeftUp => "arrow-turn-left-up.svg",
            Self::ArrowTurnRightDown => "arrow-turn-right-down.svg",
            Self::ArrowTurnRightUp => "arrow-turn-right-up.svg",
            Self::ArrowTurnUpLeft => "arrow-turn-up-left.svg",
            Self::ArrowTurnUpRight => "arrow-turn-up-right.svg",
            Self::ArrowUpCircle => "arrow-up-circle.svg",
            Self::ArrowUpLeft => "arrow-up-left.svg",
            Self::ArrowUpOnSquareStack => "arrow-up-on-square-stack.svg",
            Self::ArrowUpOnSquare => "arrow-up-on-square.svg",
            Self::ArrowUpRight => "arrow-up-right.svg",
            Self::ArrowUpTray => "arrow-up-tray.svg",
            Self::ArrowUp => "arrow-up.svg",
            Self::ArrowUturnDown => "arrow-uturn-down.svg",
            Self::ArrowUturnLeft => "arrow-uturn-left.svg",
            Self::ArrowUturnRight => "arrow-uturn-right.svg",
            Self::ArrowUturnUp => "arrow-uturn-up.svg",
            Self::ArrowsPointingIn => "arrows-pointing-in.svg",
            Self::ArrowsPointingOut => "arrows-pointing-out.svg",
            Self::ArrowsRightLeft => "arrows-right-left.svg",
            Self::ArrowsUpDown => "arrows-up-down.svg",
            Self::AtSymbol => "at-symbol.svg",
            Self::Backspace => "backspace.svg",
            Self::Backward => "backward.svg",
            Self::Banknotes => "banknotes.svg",
            Self::Bars2 => "bars-2.svg",
            Self::Bars3BottomLeft => "bars-3-bottom-left.svg",
            Self::Bars3BottomRight => "bars-3-bottom-right.svg",
            Self::Bars3CenterLeft => "bars-3-center-left.svg",
            Self::Bars3 => "bars-3.svg",
            Self::Bars4 => "bars-4.svg",
            Self::BarsArrowDown => "bars-arrow-down.svg",
            Self::BarsArrowUp => "bars-arrow-up.svg",
            Self::Battery0 => "battery-0.svg",
            Self::Battery100 => "battery-100.svg",
            Self::Battery50 => "battery-50.svg",
            Self::Beaker => "beaker.svg",
            Self::BellAlert => "bell-alert.svg",
            Self::BellSlash => "bell-slash.svg",
            Self::BellSnooze => "bell-snooze.svg",
            Self::Bell => "bell.svg",
            Self::Bold => "bold.svg",
            Self::BoltSlash => "bolt-slash.svg",
            Self::Bolt => "bolt.svg",
            Self::BookOpen => "book-open.svg",
            Self::BookmarkSlash => "bookmark-slash.svg",
            Self::BookmarkSquare => "bookmark-square.svg",
            Self::Bookmark => "bookmark.svg",
            Self::Briefcase => "briefcase.svg",
            Self::BugAnt => "bug-ant.svg",
            Self::BuildingLibrary => "building-library.svg",
            Self::BuildingOffice2 => "building-office-2.svg",
            Self::BuildingOffice => "building-office.svg",
            Self::BuildingStorefront => "building-storefront.svg",
            Self::Cake => "cake.svg",
            Self::Calculator => "calculator.svg",
            Self::CalendarDateRange => "calendar-date-range.svg",
            Self::CalendarDays => "calendar-days.svg",
            Self::Calendar => "calendar.svg",
            Self::Camera => "camera.svg",
            Self::ChartBarSquare => "chart-bar-square.svg",
            Self::ChartBar => "chart-bar.svg",
            Self::ChartPie => "chart-pie.svg",
            Self::ChatBubbleBottomCenterText => "chat-bubble-bottom-center-text.svg",
            Self::ChatBubbleBottomCenter => "chat-bubble-bottom-center.svg",
            Self::ChatBubbleLeftEllipsis => "chat-bubble-left-ellipsis.svg",
            Self::ChatBubbleLeftRight => "chat-bubble-left-right.svg",
            Self::ChatBubbleLeft => "chat-bubble-left.svg",
            Self::ChatBubbleOvalLeftEllipsis => "chat-bubble-oval-left-ellipsis.svg",
            Self::ChatBubbleOvalLeft => "chat-bubble-oval-left.svg",
            Self::CheckBadge => "check-badge.svg",
            Self::CheckCircle => "check-circle.svg",
            Self::Check => "check.svg",
            Self::ChevronDoubleDown => "chevron-double-down.svg",
            Self::ChevronDoubleLeft => "chevron-double-left.svg",
            Self::ChevronDoubleRight => "chevron-double-right.svg",
            Self::ChevronDoubleUp => "chevron-double-up.svg",
            Self::ChevronDown => "chevron-down.svg",
            Self::ChevronLeft => "chevron-left.svg",
            Self::ChevronRight => "chevron-right.svg",
            Self::ChevronUpDown => "chevron-up-down.svg",
            Self::ChevronUp => "chevron-up.svg",
            Self::CircleStack => "circle-stack.svg",
            Self::ClipboardDocumentCheck => "clipboard-document-check.svg",
            Self::ClipboardDocumentList => "clipboard-document-list.svg",
            Self::ClipboardDocument => "clipboard-document.svg",
            Self::Clipboard => "clipboard.svg",
            Self::Clock => "clock.svg",
            Self::CloudArrowDown => "cloud-arrow-down.svg",
            Self::CloudArrowUp => "cloud-arrow-up.svg",
            Self::Cloud => "cloud.svg",
            Self::CodeBracketSquare => "code-bracket-square.svg",
            Self::CodeBracket => "code-bracket.svg",
            Self::Cog6Tooth => "cog-6-tooth.svg",
            Self::Cog8Tooth => "cog-8-tooth.svg",
            Self::Cog => "cog.svg",
            Self::CommandLine => "command-line.svg",
            Self::ComputerDesktop => "computer-desktop.svg",
            Self::CpuChip => "cpu-chip.svg",
            Self::CreditCard => "credit-card.svg",
            Self::CubeTransparent => "cube-transparent.svg",
            Self::Cube => "cube.svg",
            Self::CurrencyBangladeshi => "currency-bangladeshi.svg",
            Self::CurrencyDollar => "currency-dollar.svg",
            Self::CurrencyEuro => "currency-euro.svg",
            Self::CurrencyPound => "currency-pound.svg",
            Self::CurrencyRupee => "currency-rupee.svg",
            Self::CurrencyYen => "currency-yen.svg",
            Self::CursorArrowRays => "cursor-arrow-rays.svg",
            Self::CursorArrowRipple => "cursor-arrow-ripple.svg",
            Self::DevicePhoneMobile => "device-phone-mobile.svg",
            Self::DeviceTablet => "device-tablet.svg",
            Self::Divide => "divide.svg",
            Self::DocumentArrowDown => "document-arrow-down.svg",
            Self::DocumentArrowUp => "document-arrow-up.svg",
            Self::DocumentChartBar => "document-chart-bar.svg",
            Self::DocumentCheck => "document-check.svg",
            Self::DocumentCurrencyBangladeshi => "document-currency-bangladeshi.svg",
            Self::DocumentCurrencyDollar => "document-currency-dollar.svg",
            Self::DocumentCurrencyEuro => "document-currency-euro.svg",
            Self::DocumentCurrencyPound => "document-currency-pound.svg",
            Self::DocumentCurrencyRupee => "document-currency-rupee.svg",
            Self::DocumentCurrencyYen => "document-currency-yen.svg",
            Self::DocumentDuplicate => "document-duplicate.svg",
            Self::DocumentMagnifyingGlass => "document-magnifying-glass.svg",
            Self::DocumentMinus => "document-minus.svg",
            Self::DocumentPlus => "document-plus.svg",
            Self::DocumentText => "document-text.svg",
            Self::Document => "document.svg",
            Self::EllipsisHorizontalCircle => "ellipsis-horizontal-circle.svg",
            Self::EllipsisHorizontal => "ellipsis-horizontal.svg",
            Self::EllipsisVertical => "ellipsis-vertical.svg",
            Self::EnvelopeOpen => "envelope-open.svg",
            Self::Envelope => "envelope.svg",
            Self::Equals => "equals.svg",
            Self::ExclamationCircle => "exclamation-circle.svg",
            Self::ExclamationTriangle => "exclamation-triangle.svg",
            Self::EyeDropper => "eye-dropper.svg",
            Self::EyeSlash => "eye-slash.svg",
            Self::Eye => "eye.svg",
            Self::FaceFrown => "face-frown.svg",
            Self::FaceSmile => "face-smile.svg",
            Self::Film => "film.svg",
            Self::FingerPrint => "finger-print.svg",
            Self::Fire => "fire.svg",
            Self::Flag => "flag.svg",
            Self::FolderArrowDown => "folder-arrow-down.svg",
            Self::FolderMinus => "folder-minus.svg",
            Self::FolderOpen => "folder-open.svg",
            Self::FolderPlus => "folder-plus.svg",
            Self::Folder => "folder.svg",
            Self::Forward => "forward.svg",
            Self::Funnel => "funnel.svg",
            Self::Gif => "gif.svg",
            Self::GiftTop => "gift-top.svg",
            Self::Gift => "gift.svg",
            Self::GlobeAlt => "globe-alt.svg",
            Self::GlobeAmericas => "globe-americas.svg",
            Self::GlobeAsiaAustralia => "globe-asia-australia.svg",
            Self::GlobeEuropeAfrica => "globe-europe-africa.svg",
            Self::H1 => "h1.svg",
            Self::H2 => "h2.svg",
            Self::H3 => "h3.svg",
            Self::HandRaised => "hand-raised.svg",
            Self::HandThumbDown => "hand-thumb-down.svg",
            Self::HandThumbUp => "hand-thumb-up.svg",
            Self::Hashtag => "hashtag.svg",
            Self::Heart => "heart.svg",
            Self::HomeModern => "home-modern.svg",
            Self::Home => "home.svg",
            Self::Identification => "identification.svg",
            Self::InboxArrowDown => "inbox-arrow-down.svg",
            Self::InboxStack => "inbox-stack.svg",
            Self::Inbox => "inbox.svg",
            Self::InformationCircle => "information-circle.svg",
            Self::Italic => "italic.svg",
            Self::Key => "key.svg",
            Self::Language => "language.svg",
            Self::Lifebuoy => "lifebuoy.svg",
            Self::LightBulb => "light-bulb.svg",
            Self::LinkSlash => "link-slash.svg",
            Self::Link => "link.svg",
            Self::ListBullet => "list-bullet.svg",
            Self::LockClosed => "lock-closed.svg",
            Self::LockOpen => "lock-open.svg",
            Self::MagnifyingGlassCircle => "magnifying-glass-circle.svg",
            Self::MagnifyingGlassMinus => "magnifying-glass-minus.svg",
            Self::MagnifyingGlassPlus => "magnifying-glass-plus.svg",
            Self::MagnifyingGlass => "magnifying-glass.svg",
            Self::MapPin => "map-pin.svg",
            Self::Map => "map.svg",
            Self::Megaphone => "megaphone.svg",
            Self::Microphone => "microphone.svg",
            Self::MinusCircle => "minus-circle.svg",
            Self::MinusSmall => "minus-small.svg",
            Self::Minus => "minus.svg",
            Self::Moon => "moon.svg",
            Self::MusicalNote => "musical-note.svg",
            Self::Newspaper => "newspaper.svg",
            Self::NoSymbol => "no-symbol.svg",
            Self::NumberedList => "numbered-list.svg",
            Self::PaintBrush => "paint-brush.svg",
            Self::PaperAirplane => "paper-airplane.svg",
            Self::PaperClip => "paper-clip.svg",
            Self::PauseCircle => "pause-circle.svg",
            Self::Pause => "pause.svg",
            Self::PencilSquare => "pencil-square.svg",
            Self::Pencil => "pencil.svg",
            Self::PercentBadge => "percent-badge.svg",
            Self::PhoneArrowDownLeft => "phone-arrow-down-left.svg",
            Self::PhoneArrowUpRight => "phone-arrow-up-right.svg",
            Self::PhoneXMark => "phone-x-mark.svg",
            Self::Phone => "phone.svg",
            Self::Photo => "photo.svg",
            Self::PlayCircle => "play-circle.svg",
            Self::PlayPause => "play-pause.svg",
            Self::Play => "play.svg",
            Self::PlusCircle => "plus-circle.svg",
            Self::PlusSmall => "plus-small.svg",
            Self::Plus => "plus.svg",
            Self::Power => "power.svg",
            Self::PresentationChartBar => "presentation-chart-bar.svg",
            Self::PresentationChartLine => "presentation-chart-line.svg",
            Self::Printer => "printer.svg",
            Self::PuzzlePiece => "puzzle-piece.svg",
            Self::QrCode => "qr-code.svg",
            Self::QuestionMarkCircle => "question-mark-circle.svg",
            Self::QueueList => "queue-list.svg",
            Self::Radio => "radio.svg",
            Self::ReceiptPercent => "receipt-percent.svg",
            Self::ReceiptRefund => "receipt-refund.svg",
            Self::RectangleGroup => "rectangle-group.svg",
            Self::RectangleStack => "rectangle-stack.svg",
            Self::RocketLaunch => "rocket-launch.svg",
            Self::Rss => "rss.svg",
            Self::Scale => "scale.svg",
            Self::Scissors => "scissors.svg",
            Self::ServerStack => "server-stack.svg",
            Self::Server => "server.svg",
            Self::Share => "share.svg",
            Self::ShieldCheck => "shield-check.svg",
            Self::ShieldExclamation => "shield-exclamation.svg",
            Self::ShoppingBag => "shopping-bag.svg",
            Self::ShoppingCart => "shopping-cart.svg",
            Self::SignalSlash => "signal-slash.svg",
            Self::Signal => "signal.svg",
            Self::Slash => "slash.svg",
            Self::Sparkles => "sparkles.svg",
            Self::SpeakerWave => "speaker-wave.svg",
            Self::SpeakerXMark => "speaker-x-mark.svg",
            Self::Square2Stack => "square-2-stack.svg",
            Self::Square3Stack3d => "square-3-stack-3d.svg",
            Self::Squares2x2 => "squares-2x2.svg",
            Self::SquaresPlus => "squares-plus.svg",
            Self::Star => "star.svg",
            Self::StopCircle => "stop-circle.svg",
            Self::Stop => "stop.svg",
            Self::Strikethrough => "strikethrough.svg",
            Self::Sun => "sun.svg",
            Self::Swatch => "swatch.svg",
            Self::TableCells => "table-cells.svg",
            Self::Tag => "tag.svg",
            Self::Ticket => "ticket.svg",
            Self::Trash => "trash.svg",
            Self::Trophy => "trophy.svg",
            Self::Truck => "truck.svg",
            Self::Tv => "tv.svg",
            Self::Underline => "underline.svg",
            Self::UserCircle => "user-circle.svg",
            Self::UserGroup => "user-group.svg",
            Self::UserMinus => "user-minus.svg",
            Self::UserPlus => "user-plus.svg",
            Self::User => "user.svg",
            Self::Users => "users.svg",
            Self::Variable => "variable.svg",
            Self::VideoCameraSlash => "video-camera-slash.svg",
            Self::VideoCamera => "video-camera.svg",
            Self::ViewColumns => "view-columns.svg",
            Self::ViewfinderCircle => "viewfinder-circle.svg",
            Self::Wallet => "wallet.svg",
            Self::Wifi => "wifi.svg",
            Self::Window => "window.svg",
            Self::WrenchScrewdriver => "wrench-screwdriver.svg",
            Self::Wrench => "wrench.svg",
            Self::XCircle => "x-circle.svg",
            Self::XMark => "x-mark.svg",
        }
    }

    pub fn asset_path(self) -> SharedString {
        format!("heroicons/24/outline/{}", self.file_name()).into()
    }
}

impl IconNamed for HeroIconName {
    fn path(self) -> SharedString {
        self.asset_path()
    }
}

#[allow(dead_code)]
pub fn hero_icon(icon: HeroIconName) -> Icon {
    Icon::new(icon)
}
