use gpui::{Menu, MenuItem, NoAction, OsAction, SystemMenuType, actions};

actions!(
    codux_menu,
    [
        ShowAbout,
        OpenSettings,
        CheckUpdates,
        ExportDiagnostics,
        OpenRuntimeLog,
        OpenLiveLog,
        OpenWebsite,
        OpenGithub,
        HideCodux,
        HideOthers,
        ShowAll,
        NewProject,
        OpenProjectFolder,
        CloseCurrentProject,
        CloseAllProjects,
        CloseActive,
        CloseWindow,
        QuitCodux,
        ViewTerminal,
        ViewFiles,
        ViewReview,
        ToggleProjects,
        ToggleTasks,
        OpenGitPanel,
        OpenFilesPanel,
        OpenAiPanel,
        OpenSshPanel,
        CreateSplit,
        CreateTab,
        CreateTask,
        EditorSave,
        EditorSearch,
        MinimizeWindow,
        ZoomWindow,
        ToggleFullscreen,
    ]
);

pub(crate) fn codux_menus() -> Vec<Menu> {
    vec![
        Menu {
            name: "Codux".into(),
            disabled: false,
            items: vec![
                MenuItem::action("关于 Codux", ShowAbout),
                MenuItem::action("设置...", OpenSettings),
                MenuItem::action("检查更新", CheckUpdates),
                MenuItem::separator(),
                MenuItem::os_submenu("服务", SystemMenuType::Services),
                MenuItem::separator(),
                MenuItem::action("隐藏 Codux", HideCodux),
                MenuItem::action("隐藏其他", HideOthers),
                MenuItem::action("全部显示", ShowAll),
                MenuItem::separator(),
                MenuItem::action("退出 Codux", QuitCodux),
            ],
        },
        Menu {
            name: "文件".into(),
            disabled: false,
            items: vec![
                MenuItem::action("新建项目", NewProject),
                MenuItem::action("打开文件夹...", OpenProjectFolder),
                MenuItem::separator(),
                MenuItem::action("关闭当前项目", CloseCurrentProject),
                MenuItem::action("关闭所有项目", CloseAllProjects),
                MenuItem::separator(),
                MenuItem::action("关闭当前分屏", CloseActive),
                MenuItem::action("关闭窗口", CloseWindow),
            ],
        },
        Menu {
            name: "编辑".into(),
            disabled: false,
            items: vec![
                MenuItem::os_action("撤销", NoAction, OsAction::Undo),
                MenuItem::os_action("重做", NoAction, OsAction::Redo),
                MenuItem::separator(),
                MenuItem::os_action("剪切", NoAction, OsAction::Cut),
                MenuItem::os_action("复制", NoAction, OsAction::Copy),
                MenuItem::os_action("粘贴", NoAction, OsAction::Paste),
                MenuItem::os_action("全选", NoAction, OsAction::SelectAll),
            ],
        },
        Menu {
            name: "工作区".into(),
            disabled: false,
            items: vec![
                MenuItem::action("终端", ViewTerminal),
                MenuItem::action("文件", ViewFiles),
                MenuItem::action("评审", ViewReview),
                MenuItem::separator(),
                MenuItem::action("项目侧栏", ToggleProjects),
                MenuItem::action("任务侧栏", ToggleTasks),
                MenuItem::separator(),
                MenuItem::action("新增终端分屏", CreateSplit),
                MenuItem::action("新增底部终端", CreateTab),
                MenuItem::action("新建 Worktree", CreateTask),
                MenuItem::separator(),
                MenuItem::action("保存文件", EditorSave),
                MenuItem::action("搜索文件", EditorSearch),
            ],
        },
        Menu {
            name: "视图".into(),
            disabled: false,
            items: vec![
                MenuItem::action("Git 面板", OpenGitPanel),
                MenuItem::action("文件面板", OpenFilesPanel),
                MenuItem::action("AI 面板", OpenAiPanel),
                MenuItem::action("SSH 面板", OpenSshPanel),
                MenuItem::separator(),
                MenuItem::action("切换全屏", ToggleFullscreen),
            ],
        },
        Menu {
            name: "窗口".into(),
            disabled: false,
            items: vec![
                MenuItem::action("最小化", MinimizeWindow),
                MenuItem::action("缩放", ZoomWindow),
                MenuItem::separator(),
                MenuItem::action("关闭窗口", CloseWindow),
            ],
        },
        Menu {
            name: "帮助".into(),
            disabled: false,
            items: vec![
                MenuItem::action("导出诊断...", ExportDiagnostics),
                MenuItem::action("打开 Runtime Log", OpenRuntimeLog),
                MenuItem::action("打开 Live Log", OpenLiveLog),
                MenuItem::separator(),
                MenuItem::action("官网", OpenWebsite),
                MenuItem::action("GitHub", OpenGithub),
            ],
        },
    ]
}
