use super::{MemoryLaunchArtifacts, MemoryProjectProfile, MemorySummary, normalized_non_empty};
use std::path::Path;

/// Resolve the launch-artifact paths for a project under `runtime_root`. The
/// caller owns the base directory (the desktop passes its `runtime_root_dir()`;
/// the headless host passes its own runtime root), so the engine stays free of
/// environment-specific path logic.
pub fn launch_artifact_paths(runtime_root: &Path, project_id: &str) -> MemoryLaunchArtifacts {
    let workspace_root = runtime_root
        .join("memory-workspaces")
        .join(safe_path_segment(project_id));
    MemoryLaunchArtifacts {
        prompt_file: workspace_root.join("memory-prompt.txt"),
        index_file: workspace_root.join("MEMORY.md"),
        workspace_root,
    }
}

fn safe_path_segment(value: &str) -> String {
    let segment = value
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || matches!(ch, '-' | '_' | '.') {
                ch
            } else {
                '_'
            }
        })
        .collect::<String>();
    if segment.trim_matches('_').is_empty() {
        "project".to_string()
    } else {
        segment
    }
}

pub(super) fn render_launch_memory_index(
    project_id: &str,
    project_name: &str,
    workspace_path: &str,
    summary: &MemorySummary,
    project_profile: Option<&MemoryProjectProfile>,
    global_prompt: Option<&str>,
    extra_context: Option<&str>,
) -> String {
    let mut lines = vec![
        "# Codux Memory".to_string(),
        String::new(),
        "This file is generated by the GPUI runtime bridge for AI CLI launch context.".to_string(),
        String::new(),
        format!("Project: {project_name}"),
        format!("Project ID: {project_id}"),
        format!("Workspace: {workspace_path}"),
        format!("Active entries: {}", summary.active_entries),
        format!("Core entries: {}", summary.core_entries),
        format!("Working entries: {}", summary.working_entries),
        format!("Archived entries: {}", summary.archived_entries),
        format!(
            "Project profile present: {}",
            if summary.project_profile_present {
                "yes"
            } else {
                "no"
            }
        ),
        String::new(),
        "## Recent Memory".to_string(),
    ];
    if let Some(global_prompt) = global_prompt.and_then(normalized_non_empty) {
        lines.push(String::new());
        lines.push("## Global Prompt".to_string());
        lines.push(global_prompt.to_string());
    }
    if let Some(extra_context) = extra_context.and_then(normalized_non_empty) {
        lines.push(String::new());
        lines.push("## Extra Context".to_string());
        lines.push(extra_context.to_string());
    }
    if summary.recent_entries.is_empty() {
        lines.push("- No recent memory entries are indexed.".to_string());
    } else {
        lines.extend(summary.recent_entries.iter().map(|entry| {
            format!(
                "- [{}:{}:{}:{}] {}",
                entry.scope, entry.tier, entry.kind, entry.status, entry.content
            )
        }));
    }
    if let Some(profile) = project_profile {
        lines.push(String::new());
        lines.push("## Project Profile".to_string());
        lines.push(profile.content.clone());
    }
    lines.push(String::new());
    lines.join("\n")
}

pub(super) fn render_recent_memory(summary: &MemorySummary) -> String {
    let mut lines = vec!["# Recent Memory".to_string(), String::new()];
    lines.extend(summary.recent_entries.iter().map(|entry| {
        format!(
            "- `{}` `{}` `{}` `{}` {}",
            entry.scope, entry.tier, entry.kind, entry.status, entry.content
        )
    }));
    if summary.recent_entries.is_empty() {
        lines.push("No recent memory entries are indexed.".to_string());
    }
    lines.push(String::new());
    lines.join("\n")
}
